[project]
name = "infrastructure"
version = "1.0.0"
requires-python = ">=3.13"
dependencies = [
    "aws-cdk-lib>=2.0.0",
    "constructs>=10.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["stacks"]